### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by davidmezzetti** [hynek-urban/rocketchat-async#1] opened 2023-02-25 12:53 UTC
Just wanted to say thank you for putting this project together. I'm using it for a project called [txtchat](https://github.com/neuml/txtchat). 

Everything works well so far. I might put an issue/PR in at some point to add token authentication as a login option. I've also noticed it looks like an error occurs when listening for messages and a room deletion happens. But otherwise everything is great. Thanks again for putting this out there.

**Comment by hynek-urban** [comment] 2023-03-04 15:17
Hi @davidmezetti, thanks for the kind words! It's nice to know somebody found it useful, especially since your project is quite cool :)

I'll try to fix the issues you're reporting within a week or so.

**Comment by davidmezzetti** [comment] 2023-03-05 23:52
Sounds great, the library is much appreciated. 

I've had this other issue reported: https://github.com/neuml/txtchat/issues/4

Have you by any chance ran into issues with RC closing connections or socket timeouts?

**Comment by hynek-urban** [comment] 2023-03-23 17:32
Hi @davidmezzetti , I finally got to a) fixing the room deletion crashes and b) making the library friendly for automatic reconnections (and I've updated the example in readme accordingly).

I am yet to take a look at the reported issue. But it doesn't ring any bells, from a quick glance.

**Comment by hynek-urban** [comment] 2023-06-11 19:37
I haven't been able to reproduce the discussed issue. And since token authentication has been added by @mcg88, I'm closing this ticket :)

**Closed as completed by hynek-urban** 2023-06-11 19:37 UTC
